### ISSUE TITLE
NullPointerException on calling User Info Endpoint

### ISSUE THREAD

**Issue by vrustia-owens** [wso2-extensions/identity-inbound-auth-oauth#748]
Upon successful login via open id connect, the service provider is successful in retrieving the claims from the user info endpoint. After updating the user profile or updating the Service Provider Configuration in WSO2 IS, I encountered this exception below. Upon quick inspection, the code segment and the exception implies that the cache entry is nullified because of the said actions on the UI, and since the code that triggered this doesn't handle null cache entry, therefore would cause NullPointerException on this code

Code origin of error:
https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/d89eda3083585eeed5763b2b4abf65a440c06a65/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/openidconnect/AbstractUserInfoResponseBuilder.java#L298

Exception encountered:
```
Caused by: java.lang.NullPointerException
	at org.wso2.carbon.identity.openidconnect.AbstractUserInfoResponseBuilder.getRequestObject(AbstractUserInfoResponseBuilder.java:298)
	at org.wso2.carbon.identity.openidconnect.AbstractUserInfoResponseBuilder.getResponseString(AbstractUserInfoResponseBuilder.java:82)
	at org.wso2.carbon.identity.oauth.endpoint.user.OpenIDConnectUserEndpoint.getUserClaims(OpenIDConnectUserEndpoint.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:188)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104)
```

**Comment by omindu** [comment]
Thank you for reporting this. We'll track this issue through https://github.com/wso2/product-is/issues/1953
