### ISSUE TITLE
OSGI bundle issue for OIDC logout

### ISSUE THREAD

**Issue by tbaker57** [wso2-extensions/identity-inbound-auth-oauth#889]
**Description:**

Hi there, I just wanted to report an OSGI bundling issue in the org.wso2.carbon.identity.oidc.session component.

The error is
```
TID: [-1234] [] [2018-05-23 21:57:40,668] ERROR {org.apache.catalina.core.StandardWrapperValve} -  Servlet.service() for servlet [bridgeserv
let] in context with path [/] threw exception [Servlet execution threw an exception] with root cause
java.lang.ClassNotFoundException: org.apache.commons.collections.MapUtils cannot be found by org.wso2.carbon.identity.oidc.session_5.6.63
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
```
This has actually been reported in https://wso2.org/jira/browse/IDENTITY-7359 but I'm not sure how to get an account in that Jira to comment there.

The fix (which works for me) is
```
diff --git a/components/org.wso2.carbon.identity.oidc.session/pom.xml b/components/org.wso2.carbon.identity.oidc.session/pom.xml
index bbb4b53..6ef4d6c 100644
--- a/components/org.wso2.carbon.identity.oidc.session/pom.xml
+++ b/components/org.wso2.carbon.identity.oidc.session/pom.xml
@@ -155,6 +155,7 @@
                             org.apache.commons.lang; version="${commons-lang.wso2.osgi.version.range}",
                             org.apache.commons.lang.text; version="${commons-lang.wso2.osgi.version.range}",
                             org.apache.commons.logging.*; version="${commons-logging.osgi.version.range}",
+                            org.apache.commons.collections; version="${commons-collections.wso2.osgi.version.range}",
                             org.apache.http.*,
 
                             com.nimbusds.jose.*; version="${nimbusds.osgi.version.range}",
@@ -261,4 +262,4 @@
         </plugins>
     </build>
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
5.6.63 (probably others)

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

Login via OIDC and then hit /oidc/logout on the WSO2 IS.

**Related Issues:**

**Comment by tbaker57** [comment]
Looks like it has been fixed in the latest version - sorry for the noise...
